

import multiprocessing
from PyQt5 import QtCore, QtGui, QtWidgets
from bs4 import BeautifulSoup 
import re
import sqlite3
from time import sleep
import requests 
import json
from datetime import date
from search_psn import *
from search_steam import *
from search_eshop import *
from search_nuuvem import *
from inserir_dados import *
from db_jogos import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1297, 887)
        Form.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1421, 891))
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1301, 871))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_1.setGeometry(QtCore.QRect(0, 80, 1291, 761))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tableWidget_1.setFont(font)
        self.tableWidget_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Arial\";")
        self.tableWidget_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(6)
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(5, item)
        self.tableWidget_1.setColumnWidth(0,150)
        self.tableWidget_1.setColumnWidth(1,350)
        self.tableWidget_1.setColumnWidth(2,100)
        self.tableWidget_1.setColumnWidth(3,100)
        self.tableWidget_1.setColumnWidth(4,100)
        self.tableWidget_1.setColumnWidth(5,400)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 10, 151, 23))
        self.pushButton_2.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.limpar_tabela_eshop)
        self.pushButton_1 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 10, 151, 23))
        self.pushButton_1.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_1.clicked.connect(self.eshop)
        self.progressBar_1 = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar_1.setGeometry(QtCore.QRect(20, 40, 361, 23))
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setObjectName("progressBar_1")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 80, 1291, 761))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Arial\";")
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.setColumnWidth(0,150)
        self.tableWidget_2.setColumnWidth(1,350)
        self.tableWidget_2.setColumnWidth(2,100)
        self.tableWidget_2.setColumnWidth(3,100)
        self.tableWidget_2.setColumnWidth(4,100)
        self.tableWidget_2.setColumnWidth(5,400)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 10, 151, 23))
        self.pushButton_4.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.limpar_tabela_nuuvem)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 10, 151, 23))
        self.pushButton_3.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.nuuvem)
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab_6)
        self.progressBar_2.setGeometry(QtCore.QRect(20, 40, 361, 23))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 80, 1291, 761))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Arial\";")
        self.tableWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.setColumnWidth(0,150)
        self.tableWidget_3.setColumnWidth(1,350)
        self.tableWidget_3.setColumnWidth(2,100)
        self.tableWidget_3.setColumnWidth(3,100)
        self.tableWidget_3.setColumnWidth(4,100)
        self.tableWidget_3.setColumnWidth(5,400)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 10, 151, 23))
        self.pushButton_5.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.psn)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 10, 151, 23))
        self.pushButton_6.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.limpar_tabela_psn)
        self.progressBar_3 = QtWidgets.QProgressBar(self.tab_4)
        self.progressBar_3.setGeometry(QtCore.QRect(20, 40, 361, 23))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 80, 1291, 761))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Arial\";")
        self.tableWidget_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.tableWidget_4.setColumnWidth(0,150)
        self.tableWidget_4.setColumnWidth(1,350)
        self.tableWidget_4.setColumnWidth(2,100)
        self.tableWidget_4.setColumnWidth(3,100)
        self.tableWidget_4.setColumnWidth(4,100)
        self.tableWidget_4.setColumnWidth(5,400)
        self.progressBar_4 = QtWidgets.QProgressBar(self.tab_5)
        self.progressBar_4.setGeometry(QtCore.QRect(20, 40, 361, 23))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName("progressBar_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 10, 151, 23))
        self.pushButton_7.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.limpar_tabela_steam)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 10, 151, 23))
        self.pushButton_8.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.steam)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 501, 20))
        self.lineEdit.setObjectName("lineEdit")
        
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(1080, 10, 101, 23))
        self.pushButton_10.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.pesquisa_db)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label.setStyleSheet("font: 10pt \"Arial\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(610, 10, 61, 21))
        self.label_2.setStyleSheet("font: 10pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 60, 1291, 801))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Arial\";")
        self.tableWidget_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_5.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(8)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        self.tableWidget_5.setColumnWidth(0,100)
        self.tableWidget_5.setColumnWidth(1,100)
        self.tableWidget_5.setColumnWidth(2,230)
        self.tableWidget_5.setColumnWidth(3,90)
        self.tableWidget_5.setColumnWidth(4,100)
        self.tableWidget_5.setColumnWidth(5,90)
        self.tableWidget_5.setColumnWidth(6,90)
        self.tableWidget_5.setColumnWidth(7,400)
        self.comboBox_1 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_1.setGeometry(QtCore.QRect(660, 10, 71, 22))
        self.comboBox_1.setStyleSheet("font: 10pt \"Arial\";")
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(740, 10, 61, 21))
        self.label_3.setStyleSheet("font: 10pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(790, 10, 71, 22))
        self.comboBox_2.setStyleSheet("font: 10pt \"Arial\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(1190, 10, 91, 23))
        self.pushButton_9.setStyleSheet("font: italic 10pt \"Arial\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.limpar_tabela_db)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Data"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nome"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Preço Original"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("Form", "% Desconto"))
        item = self.tableWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Preço Atual"))
        item = self.tableWidget_1.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Link"))
        self.pushButton_2.setText(_translate("Form", "Limpar tabela"))
        self.pushButton_1.setText(_translate("Form", "Pesquisar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "ESHOP"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Data"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nome"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Preço Original"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "% Desconto"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Preço Atual"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Link"))
        self.pushButton_4.setText(_translate("Form", "Limpar tabela"))
        self.pushButton_3.setText(_translate("Form", "Pesquisar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "NUUVEM"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Tipo"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nome"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Preço Original"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form", "% Desconto"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Preço Atual"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Link"))
        self.pushButton_5.setText(_translate("Form", "Pesquisar"))
        self.pushButton_6.setText(_translate("Form", "Limpar tabela"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "PLAYSTATION"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Data"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nome"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Preço Original"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Form", "% Desconto"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Preço Atual"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Link"))
        self.pushButton_7.setText(_translate("Form", "Limpar tabela"))
        self.pushButton_8.setText(_translate("Form", "Pesquisar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "STEAM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "PESQUISA"))
        self.pushButton_10.setText(_translate("Form", "Pesquisar"))
        self.label.setText(_translate("Form", "Pesquisa:"))
        self.label_2.setText(_translate("Form", "Loja:"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Loja"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Preço Original"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "% Desconto"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Preço Atual"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Link"))
        self.comboBox_1.setItemText(0, _translate("Form", "Todos"))
        self.comboBox_1.setItemText(1, _translate("Form", "PSN"))
        self.comboBox_1.setItemText(2, _translate("Form", "EShop"))
        self.comboBox_1.setItemText(3, _translate("Form", "Steam"))
        self.comboBox_1.setItemText(4, _translate("Form", "Nuuvem"))
        self.label_3.setText(_translate("Form", "Filtro:"))
        self.comboBox_2.setItemText(0, _translate("Form", "Data"))
        self.comboBox_2.setItemText(1, _translate("Form", "Desconto"))
        self.comboBox_2.setItemText(2, _translate("Form", "Nome"))
        self.comboBox_2.setItemText(3, _translate("Form", "Preço"))
        self.comboBox_2.setItemText(4, _translate("Form", "Tipo"))
        self.pushButton_9.setText(_translate("Form", "Limpar tabela"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "BANCO DE DADOS"))

    def eshop(self):
        self.progressBar_1.setProperty("value", 1)
        eshopjogo()
        self.loadataeshop()
        self.progressBar_1.setProperty("value", 100)
    def nuuvem(self):
        self.progressBar_2.setProperty("value", 1)
        nuuvemgame()
        self.loadatanuuvem()
        self.progressBar_2.setProperty("value", 100)
    def psn(self):
        self.progressBar_3.setProperty("value", 1)
        psnjogo()
        self.loadatapsn()
        self.progressBar_3.setProperty("value", 100)
    def steam(self):
        self.progressBar_4.setProperty("value", 1)
        steam_()
        self.loadatasteam()
        self.progressBar_4.setProperty("value", 100)

    def loadataeshop(self):    
        for row , r in enumerate (rowlisteshop):    
            loja,jogo,preco,pdesconto,poriginal,linkcompleto,tipo=r
           
            inserir_banco(loja,jogo,preco,pdesconto,poriginal,linkcompleto,tipo)
            self.tableWidget_1.setRowCount(len(rowlisteshop))
            self.tableWidget_1.setItem(row,1,QtWidgets.QTableWidgetItem(f'{jogo}'))
            self.tableWidget_1.setItem(row,2,QtWidgets.QTableWidgetItem(f'R${poriginal.replace(".",",")}'))#paginas
            self.tableWidget_1.setItem(row,3,QtWidgets.QTableWidgetItem(f'{pdesconto}%'))
            self.tableWidget_1.setItem(row,4,QtWidgets.QTableWidgetItem(f'R${preco.replace(".",",")}'))
            self.tableWidget_1.setItem(row,5,QtWidgets.QTableWidgetItem(f'{linkcompleto}'))
            self.tableWidget_1.setItem(row,0,QtWidgets.QTableWidgetItem(f'{tipo}'))
    
    def limpar_tabela_eshop(self):
        self.tableWidget_1.clearContents()
        rowlisteshop.clear()
        self.loadataeshop()  
        self.progressBar_1.setProperty("value", 0)
    
    def loadatanuuvem(self):    
        for row , r in enumerate (rowlistnuuvem):    
            loja,jogo,preco,pdesconto,poriginal,linkcompleto,tipo=r
            inserir_banco(loja,jogo,preco,pdesconto,poriginal,linkcompleto,tipo)
            
            self.tableWidget_2.setRowCount(len(rowlistnuuvem))
            self.tableWidget_2.setItem(row,1,QtWidgets.QTableWidgetItem(f'{jogo}'))
            self.tableWidget_2.setItem(row,2,QtWidgets.QTableWidgetItem(f'R${poriginal.replace(".",",")}'))#paginas
            self.tableWidget_2.setItem(row,3,QtWidgets.QTableWidgetItem(f'{pdesconto}%'))
            self.tableWidget_2.setItem(row,4,QtWidgets.QTableWidgetItem(f'R${preco.replace(".",",")}'))
            self.tableWidget_2.setItem(row,5,QtWidgets.QTableWidgetItem(f'{linkcompleto}'))
            self.tableWidget_2.setItem(row,0,QtWidgets.QTableWidgetItem(f'{tipo}'))
            

    def limpar_tabela_nuuvem(self):
        self.tableWidget_2.clearContents()
        rowlistnuuvem.clear()
        self.loadatanuuvem()  
        self.progressBar_2.setProperty("value", 0)

    def loadatapsn(self):    
        for row , r in enumerate (rowlistpsn):    
            loja,jogo,preco,pdesconto,poriginal,linkcompleto,tipo=r
            inserir_banco(loja,jogo,preco,pdesconto,poriginal,linkcompleto,tipo)
            self.tableWidget_3.setRowCount(len(rowlistpsn))
            self.tableWidget_3.setItem(row,1,QtWidgets.QTableWidgetItem(f'{jogo}'))
            self.tableWidget_3.setItem(row,2,QtWidgets.QTableWidgetItem(f'R${poriginal.replace(".",",")}'))#paginas
            self.tableWidget_3.setItem(row,3,QtWidgets.QTableWidgetItem(f'{pdesconto}%'))
            self.tableWidget_3.setItem(row,4,QtWidgets.QTableWidgetItem(f'R${preco.replace(".",",")}'))
            self.tableWidget_3.setItem(row,5,QtWidgets.QTableWidgetItem(f'{linkcompleto}'))
            self.tableWidget_3.setItem(row,0,QtWidgets.QTableWidgetItem(f'{tipo}'))
            
    def limpar_tabela_psn(self):
        self.tableWidget_3.clearContents()
        rowlistpsn.clear()
        self.loadatapsn()  
        self.progressBar_3.setProperty("value", 0)
        
    def loadatasteam(self):    
        for row , r in enumerate (rowliststeam):    
            loja,jogo,preco,pdesconto,poriginal,linkcompleto,tipo=r
            
            inserir_banco(loja,jogo,preco,pdesconto,poriginal,linkcompleto,tipo)
            self.tableWidget_4.setRowCount(len(rowliststeam))
            self.tableWidget_4.setItem(row,1,QtWidgets.QTableWidgetItem(f'{jogo}'))
            self.tableWidget_4.setItem(row,2,QtWidgets.QTableWidgetItem(f'R${poriginal.replace(".",",")}'))#paginas
            self.tableWidget_4.setItem(row,3,QtWidgets.QTableWidgetItem(f'{pdesconto}%'))
            self.tableWidget_4.setItem(row,4,QtWidgets.QTableWidgetItem(f'R${preco.replace(".",",")}'))
            self.tableWidget_4.setItem(row,5,QtWidgets.QTableWidgetItem(f'{linkcompleto}'))
            self.tableWidget_4.setItem(row,0,QtWidgets.QTableWidgetItem(f'{tipo}'))
            
   
    def limpar_tabela_steam(self):
        self.tableWidget_4.clearContents()
        rowliststeam.clear()
        self.loadatasteam() 
        self.progressBar_4.setProperty("value", 0) 

    def loadata_banco(self):    
        for row , r in enumerate (rowlist_banco):    
            loja,data,jogo,preco,pdesconto,poriginal,linkcompleto,tipo=r
            self.tableWidget_5.setRowCount(len(rowlist_banco))
            self.tableWidget_5.setItem(row,0,QtWidgets.QTableWidgetItem(f'{loja.upper()}'))
            self.tableWidget_5.setItem(row,1,QtWidgets.QTableWidgetItem(f'{data}'))
            self.tableWidget_5.setItem(row,2,QtWidgets.QTableWidgetItem(f'{jogo}'))
            self.tableWidget_5.setItem(row,3,QtWidgets.QTableWidgetItem(f'{tipo}'))#pagina
            self.tableWidget_5.setItem(row,4,QtWidgets.QTableWidgetItem(f'R${poriginal}'))#paginas
            self.tableWidget_5.setItem(row,5,QtWidgets.QTableWidgetItem(f'{pdesconto}%'))
            self.tableWidget_5.setItem(row,6,QtWidgets.QTableWidgetItem(f'R${preco}'))
            self.tableWidget_5.setItem(row,7,QtWidgets.QTableWidgetItem(f'{linkcompleto}'))
    def limpar_tabela_db(self):
        self.tableWidget_5.clearContents()
        rowlist_banco.clear()
        self.loadata_banco()  
        

    def pesquisa_db(self):
        self.tableWidget_5.clearContents()
        rowlist_banco.clear()
        loja_pesquisa=self.comboBox_1.currentText()
        filtro=self.comboBox_2.currentText()
        pesquisa_line=self.lineEdit.text()
        pesquisa_banco(pesquisa_line,loja_pesquisa,filtro)
        self.loadata_banco()
        
if __name__ == "__main__":
        def criar_banco():
                try:
                        conexao=sqlite3.connect("jogos.db")
                        cursor=conexao.cursor()
                        
                        cursor.execute('''CREATE TABLE psn
                                (loja TEXT,jogo TEXT,preco TEXTL, pdesconto TEXT, poriginal TEXT, linkcompleto TEXT,  tipo TEXT , data TEXT)''')
                        cursor.execute('''CREATE TABLE steam
                                (loja TEXT,jogo TEXT,preco TEXTL, pdesconto TEXT, poriginal TEXT, linkcompleto TEXT,  tipo TEXT , data TEXT)''')
                        cursor.execute('''CREATE TABLE nuuvem
                                (loja TEXT,jogo TEXT,preco TEXTL, pdesconto TEXT, poriginal TEXT, linkcompleto TEXT,  tipo TEXT , data TEXT)''')
                        cursor.execute('''CREATE TABLE eshop
                                (loja TEXT,jogo TEXT,preco TEXTL, pdesconto TEXT, poriginal TEXT, linkcompleto TEXT,  tipo TEXT , data TEXT)''')
                        conexao.commit()
                        cursor.close()
                        conexao.close()
                        print('criou')
                except:
                        print("ja tinha criado")
        import sys
        criar_banco()
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())
